"use client"

import React, { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Switch } from '@/components/ui/switch'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { 
  Shield, 
  Smartphone, 
  Key, 
  Copy, 
  RefreshCw, 
  CheckCircle, 
  AlertTriangle,
  QrCode,
  Download,
  Trash2,
  Settings,
  Clock,
  X,
  Monitor,
  Tablet
} from 'lucide-react'
import { toast } from 'sonner'

interface BackupCode {
  id: string
  code: string
  used: boolean
  usedAt?: Date
}

interface TrustedDevice {
  id: string
  name: string
  type: 'desktop' | 'mobile' | 'tablet'
  lastUsed: string
  location: string
  isCurrentDevice: boolean
}

export default function TwoFactorAuth() {
  const [is2FAEnabled, setIs2FAEnabled] = useState(false)
  const [showSetup, setShowSetup] = useState(false)
  const [setupStep, setSetupStep] = useState(1)
  const [secretKey, setSecretKey] = useState('')
  const [qrCodeUrl, setQrCodeUrl] = useState('')
  const [verificationCode, setVerificationCode] = useState('')
  const [isVerifying, setIsVerifying] = useState(false)
  
  const [backupCodes, setBackupCodes] = useState<BackupCode[]>([])
  const [trustedDevices, setTrustedDevices] = useState<TrustedDevice[]>([
    {
      id: '1',
      name: 'Chrome on Windows',
      type: 'desktop',
      lastUsed: '2025-01-23T10:30:00Z',
      location: 'Ho Chi Minh City, Vietnam',
      isCurrentDevice: true
    },
    {
      id: '2',
      name: 'Safari on iPhone',
      type: 'mobile',
      lastUsed: '2025-01-22T15:20:00Z',
      location: 'Ho Chi Minh City, Vietnam',
      isCurrentDevice: false
    }
  ])

  useEffect(() => {
    // Simulate checking 2FA status
    const check2FAStatus = async () => {
      // In real app, this would be an API call
      const status = localStorage.getItem('2fa_enabled') === 'true'
      setIs2FAEnabled(status)
      
      if (status) {
        // Load backup codes
        generateBackupCodes()
      }
    }
    
    check2FAStatus()
  }, [])

  const generateSecretKey = () => {
    // Generate a random secret key (in real app, this would come from server)
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
    let result = ''
    for (let i = 0; i < 32; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length))
    }
    return result
  }

  const startSetup = () => {
    const secret = generateSecretKey()
    setSecretKey(secret)
    
    // Generate QR code URL (in real app, this would be generated by server)
    const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=otpauth://totp/Timona:user@example.com?secret=${secret}&issuer=Timona`
    setQrCodeUrl(qrUrl)
    
    setShowSetup(true)
    setSetupStep(1)
  }

  const verifySetup = async () => {
    if (!verificationCode.trim()) {
      toast.error('Vui lòng nhập mã xác thực')
      return
    }

    setIsVerifying(true)
    
    try {
      // Simulate API call to verify TOTP code
      await new Promise(resolve => setTimeout(resolve, 1000))
      
      // In real app, server would verify the TOTP code
      if (verificationCode === '123456' || verificationCode.length === 6) {
        setIs2FAEnabled(true)
        localStorage.setItem('2fa_enabled', 'true')
        generateBackupCodes()
        setSetupStep(3)
        toast.success('2FA đã được kích hoạt thành công!')
      } else {
        toast.error('Mã xác thực không chính xác')
      }
    } catch (error) {
      toast.error('Có lỗi xảy ra khi xác thực')
    } finally {
      setIsVerifying(false)
    }
  }

  const disable2FA = async () => {
    if (!confirm('Bạn có chắc chắn muốn tắt 2FA? Điều này sẽ làm giảm bảo mật tài khoản.')) {
      return
    }

    try {
      // Simulate API call
      await new Promise(resolve => setTimeout(resolve, 1000))
      
      setIs2FAEnabled(false)
      localStorage.setItem('2fa_enabled', 'false')
      setBackupCodes([])
      setShowSetup(false)
      toast.success('2FA đã được tắt')
    } catch (error) {
      toast.error('Có lỗi xảy ra khi tắt 2FA')
    }
  }

  const generateBackupCodes = () => {
    const codes: BackupCode[] = []
    for (let i = 0; i < 10; i++) {
      codes.push({
        id: `backup_${i + 1}`,
        code: Math.random().toString(36).substring(2, 10).toUpperCase(),
        used: Math.random() > 0.8 // Randomly mark some as used for demo
      })
    }
    setBackupCodes(codes)
  }

  const regenerateBackupCodes = () => {
    if (!confirm('Tạo mới backup codes sẽ vô hiệu hóa tất cả codes cũ. Bạn có chắc chắn?')) {
      return
    }
    
    generateBackupCodes()
    toast.success('Đã tạo mới backup codes')
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
    toast.success('Đã sao chép!')
  }

  const downloadBackupCodes = () => {
    const codesText = backupCodes
      .map(code => `${code.code} ${code.used ? '(Đã sử dụng)' : ''}`)
      .join('\n')
    
    const blob = new Blob([
      `Timona - Backup Codes\nTạo ngày: ${new Date().toLocaleDateString('vi-VN')}\n\n${codesText}`
    ], { type: 'text/plain' })
    
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'timona-backup-codes.txt'
    a.click()
    URL.revokeObjectURL(url)
    
    toast.success('Đã tải xuống backup codes')
  }

  const removeTrustedDevice = (deviceId: string) => {
    if (!confirm('Xóa thiết bị này khỏi danh sách tin cậy?')) return
    
    setTrustedDevices(devices => devices.filter(d => d.id !== deviceId))
    toast.success('Đã xóa thiết bị khỏi danh sách tin cậy')
  }

  const getDeviceIcon = (type: string) => {
    switch (type) {
      case 'mobile': return '📱'
      case 'tablet': return '📱'
      default: return '💻'
    }
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <div className="flex items-center justify-center w-10 h-10 bg-green-100 rounded-lg">
          <Shield className="w-5 h-5 text-green-600" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Two-Factor Authentication</h1>
          <p className="text-gray-600">Tăng cường bảo mật tài khoản với xác thực 2 bước</p>
        </div>
      </div>

      {/* Status Card */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Shield className="w-5 h-5" />
                Trạng Thái 2FA
              </CardTitle>
              <CardDescription>
                {is2FAEnabled 
                  ? 'Xác thực 2 bước đã được kích hoạt cho tài khoản của bạn' 
                  : 'Xác thực 2 bước chưa được kích hoạt'}
              </CardDescription>
            </div>
            
            <div className="flex items-center gap-3">
              <Badge variant={is2FAEnabled ? "default" : "secondary"} className="gap-1">
                {is2FAEnabled ? (
                  <CheckCircle className="w-3 h-3" />
                ) : (
                  <AlertTriangle className="w-3 h-3" />
                )}
                {is2FAEnabled ? 'Đã Kích Hoạt' : 'Chưa Kích Hoạt'}
              </Badge>
              
              {!is2FAEnabled ? (
                <Button onClick={startSetup}>
                  Kích Hoạt 2FA
                </Button>
              ) : (
                <Button variant="destructive" onClick={disable2FA}>
                  Tắt 2FA
                </Button>
              )}
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Setup Process */}
      {showSetup && !is2FAEnabled && (
        <Card>
          <CardHeader>
            <CardTitle>Thiết Lập 2FA</CardTitle>
            <CardDescription>
              Làm theo các bước bên dưới để kích hoạt xác thực 2 bước
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              {/* Step 1: Download App */}
              <div className={`flex items-start gap-4 p-4 rounded-lg ${
                setupStep >= 1 ? 'bg-blue-50 border border-blue-200' : 'bg-gray-50'
              }`}>
                <div className={`flex items-center justify-center w-8 h-8 rounded-full ${
                  setupStep >= 1 ? 'bg-blue-600 text-white' : 'bg-gray-400 text-white'
                }`}>
                  1
                </div>
                <div className="flex-1">
                  <h4 className="font-medium mb-2">Tải Ứng Dụng Authenticator</h4>
                  <p className="text-sm text-gray-600 mb-3">
                    Tải một trong các ứng dụng sau về điện thoại:
                  </p>
                  <div className="flex gap-2">
                    <Badge variant="outline">Google Authenticator</Badge>
                    <Badge variant="outline">Microsoft Authenticator</Badge>
                    <Badge variant="outline">Authy</Badge>
                  </div>
                </div>
              </div>

              {/* Step 2: Scan QR Code */}
              <div className={`flex items-start gap-4 p-4 rounded-lg ${
                setupStep >= 2 ? 'bg-blue-50 border border-blue-200' : 'bg-gray-50'
              }`}>
                <div className={`flex items-center justify-center w-8 h-8 rounded-full ${
                  setupStep >= 2 ? 'bg-blue-600 text-white' : 'bg-gray-400 text-white'
                }`}>
                  2
                </div>
                <div className="flex-1">
                  <h4 className="font-medium mb-2">Quét Mã QR</h4>
                  <p className="text-sm text-gray-600 mb-3">
                    Sử dụng ứng dụng authenticator để quét mã QR hoặc nhập secret key
                  </p>
                  
                  <div className="flex flex-col md:flex-row gap-4">
                    {qrCodeUrl && (
                      <div className="text-center">
                        <img 
                          src={qrCodeUrl} 
                          alt="QR Code" 
                          className="mx-auto border rounded-lg"
                        />
                        <p className="text-xs text-gray-500 mt-2">QR Code</p>
                      </div>
                    )}
                    
                    <div className="flex-1">
                      <Label>Secret Key (nhập thủ công nếu không quét được QR)</Label>
                      <div className="flex items-center gap-2 mt-1">
                        <Input 
                          value={secretKey} 
                          readOnly 
                          className="font-mono text-sm"
                        />
                        <Button
                          variant="outline"
                          size="icon"
                          onClick={() => copyToClipboard(secretKey)}
                        >
                          <Copy className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                  </div>
                  
                  <Button 
                    className="mt-3" 
                    onClick={() => setSetupStep(2)}
                    disabled={setupStep >= 2}
                  >
                    Đã Quét Xong
                  </Button>
                </div>
              </div>

              {/* Step 3: Verify */}
              {setupStep >= 2 && (
                <div className="flex items-start gap-4 p-4 rounded-lg bg-blue-50 border border-blue-200">
                  <div className="flex items-center justify-center w-8 h-8 rounded-full bg-blue-600 text-white">
                    3
                  </div>
                  <div className="flex-1">
                    <h4 className="font-medium mb-2">Xác Thực</h4>
                    <p className="text-sm text-gray-600 mb-3">
                      Nhập mã 6 số từ ứng dụng authenticator để hoàn tất thiết lập
                    </p>
                    
                    <div className="flex items-center gap-2 max-w-xs">
                      <Input
                        placeholder="123456"
                        value={verificationCode}
                        onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
                        className="text-center font-mono text-lg"
                      />
                      <Button 
                        onClick={verifySetup}
                        disabled={isVerifying || verificationCode.length !== 6}
                      >
                        {isVerifying ? 'Đang xác thực...' : 'Xác Thực'}
                      </Button>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {/* 2FA Management */}
      {is2FAEnabled && (
        <Tabs defaultValue="backup-codes">
          <TabsList>
            <TabsTrigger value="backup-codes">Backup Codes</TabsTrigger>
            <TabsTrigger value="trusted-devices">Thiết Bị Tin Cậy</TabsTrigger>
            <TabsTrigger value="settings">Cài Đặt</TabsTrigger>
          </TabsList>

          <TabsContent value="backup-codes">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>Backup Codes</CardTitle>
                    <CardDescription>
                      Sử dụng các mã này để đăng nhập khi không có điện thoại
                    </CardDescription>
                  </div>
                  
                  <div className="flex items-center gap-2">
                    <Button variant="outline" onClick={downloadBackupCodes}>
                      <Download className="w-4 h-4 mr-2" />
                      Tải Xuống
                    </Button>
                    <Button variant="outline" onClick={regenerateBackupCodes}>
                      <RefreshCw className="w-4 h-4 mr-2" />
                      Tạo Mới
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-4">
                  <div className="flex items-start gap-2">
                    <AlertTriangle className="w-5 h-5 text-yellow-600 mt-0.5" />
                    <div>
                      <p className="font-medium text-yellow-800">Lưu ý quan trọng:</p>
                      <p className="text-sm text-yellow-700">
                        Mỗi backup code chỉ có thể sử dụng một lần. Hãy lưu trữ chúng ở nơi an toàn.
                      </p>
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {backupCodes.map((backup) => (
                    <div 
                      key={backup.id}
                      className={`flex items-center justify-between p-3 border rounded-lg ${
                        backup.used ? 'bg-gray-50 opacity-50' : 'bg-white'
                      }`}
                    >
                      <span className={`font-mono ${backup.used ? 'line-through' : ''}`}>
                        {backup.code}
                      </span>
                      <div className="flex items-center gap-2">
                        {backup.used ? (
                          <Badge variant="secondary">Đã dùng</Badge>
                        ) : (
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => copyToClipboard(backup.code)}
                          >
                            <Copy className="w-4 h-4" />
                          </Button>
                        )}
                      </div>
                    </div>
                  ))}
                </div>

                <div className="mt-4 text-sm text-gray-600">
                  <p>
                    Còn lại: <strong>{backupCodes.filter(c => !c.used).length}</strong> codes chưa sử dụng
                  </p>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="trusted-devices">
            <Card>
              <CardHeader>
                <CardTitle>Thiết Bị Tin Cậy</CardTitle>
                <CardDescription>
                  Quản lý các thiết bị đã được đánh dấu tin cậy
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {trustedDevices.map((device) => (
                    <div key={device.id} className="flex items-center justify-between p-4 border rounded-lg">
                      <div className="flex items-center gap-3">
                        <span className="text-2xl">{getDeviceIcon(device.type)}</span>
                        <div>
                          <div className="flex items-center gap-2">
                            <p className="font-medium">{device.name}</p>
                            {device.isCurrentDevice && (
                              <Badge variant="outline">Thiết bị hiện tại</Badge>
                            )}
                          </div>
                          <p className="text-sm text-gray-600">
                            {device.location} • Lần cuối: {new Date(device.lastUsed).toLocaleDateString('vi-VN')}
                          </p>
                        </div>
                      </div>
                      
                      {!device.isCurrentDevice && (
                        <Button
                          variant="destructive"
                          size="sm"
                          onClick={() => removeTrustedDevice(device.id)}
                        >
                          <Trash2 className="w-4 h-4 mr-1" />
                          Xóa
                        </Button>
                      )}
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="settings">
            <Card>
              <CardHeader>
                <CardTitle>Cài Đặt 2FA</CardTitle>
                <CardDescription>
                  Tùy chỉnh các cài đặt xác thực 2 bước
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="flex items-center justify-between">
                  <div>
                    <Label className="text-base font-medium">Yêu cầu 2FA cho đăng nhập</Label>
                    <p className="text-sm text-gray-600">
                      Luôn yêu cầu mã 2FA khi đăng nhập
                    </p>
                  </div>
                  <Switch checked={true} disabled />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label className="text-base font-medium">Yêu cầu 2FA cho thanh toán</Label>
                    <p className="text-sm text-gray-600">
                      Yêu cầu xác thực khi thực hiện giao dịch tài chính
                    </p>
                  </div>
                  <Switch defaultChecked />
                </div>

                <div className="flex items-center justify-between">
                  <div>
                    <Label className="text-base font-medium">Nhớ thiết bị trong 30 ngày</Label>
                    <p className="text-sm text-gray-600">
                      Không yêu cầu 2FA trên thiết bị tin cậy
                    </p>
                  </div>
                  <Switch defaultChecked />
                </div>

                <div className="pt-4 border-t">
                  <Button variant="destructive" onClick={disable2FA}>
                    <Shield className="w-4 h-4 mr-2" />
                    Tắt 2FA
                  </Button>
                </div>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      )}

      {/* Security Tips */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Shield className="w-5 h-5" />
            Mẹo Bảo Mật
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3 text-sm">
            <div className="flex items-start gap-2">
              <CheckCircle className="w-4 h-4 text-green-600 mt-0.5" />
              <p>Sử dụng ứng dụng authenticator thay vì SMS để tăng tính bảo mật</p>
            </div>
            <div className="flex items-start gap-2">
              <CheckCircle className="w-4 h-4 text-green-600 mt-0.5" />
              <p>Lưu trữ backup codes ở nơi an toàn, tách biệt với thiết bị chính</p>
            </div>
            <div className="flex items-start gap-2">
              <CheckCircle className="w-4 h-4 text-green-600 mt-0.5" />
              <p>Không chia sẻ mã 2FA với bất kỳ ai, kể cả nhân viên hỗ trợ</p>
            </div>
            <div className="flex items-start gap-2">
              <CheckCircle className="w-4 h-4 text-green-600 mt-0.5" />
              <p>Thường xuyên kiểm tra và xóa các thiết bị không còn sử dụng</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
