on:
  push:
name: Deploy Frontend V2
jobs:
  web-deploy:
    name: Deploy with ISR
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Check if dist folder exists
        id: check-dist
        run: |
          if [ -d "./dist/frontend" ]; then
            echo "Dist folder exists, skipping build"
            echo "skip_build=true" >> $GITHUB_ENV
          else
            echo "Dist folder not found, running build"
            echo "skip_build=false" >> $GITHUB_ENV
          fi
      - name: Install dependencies & Build (if needed)
        if: env.skip_build == 'false'
        run: |
          npm install --force
          npm i @rollup/rollup-linux-x64-gnu --force
          npm run build -- --configuration production --prerender

      - name: Sync build folder only
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: tazagroup.vn
          username: tazaspac@tazagroup.vn
          password: '@Taza#Group*2020'
          local-dir: ./dist/frontend/ # <-- Specify the local "build" folder
          server-dir: public_html/addonwebsite/v2tazagroup/site/  # Destination on server
          
