on:
  push:
name: Deploy Frontend V2
jobs:
  web-deploy:
    name: Deploy with ISR
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Install dependencies & Build
        run: |
          npm install --force
          npm i @rollup/rollup-linux-x64-gnu --force
          npm run build -- --configuration production --prerender

      - name: Sync build folder only
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: tazagroup.vn
          username: tazaspac
          password: '@Taza#Group*2020'
          local-dir: ./dist/frontend/ # <-- Specify the local "build" folder
          server-dir: public_html/addonwebsite/v2tazagroup/site/  # Destination on server
          
